fastlane_version "2.68.2"
default_platform :ios

platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore", readonly: true)
    build_ios_app(project: "build-ios/fuse2048.xcodeproj")
    upload_to_testflight
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # sync_code_signing(type: "appstore", readonly: true)
    capture_screenshots
    build_ios_app(project: "build-ios/fuse2048.xcodeproj")
    upload_to_app_store(force: true)
    # frame_screenshots
  end
end
